name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_contracts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        contract: [token, database, sage]

    steps:
    - uses: actions/checkout@v3
    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
        components: rust-src
    - name: Install wasm
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      working-directory: ./contracts/${{ matrix.contract }}
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./contracts/${{ matrix.contract }}
      run: cargo test --verbose
