name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup_rust:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
        components: rust-src
    - name: Install wasm
      run: rustup target add wasm32-unknown-unknown
    
  
  test_token:
    needs: setup_rust
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./contracts/token
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./contracts/token
      run: cargo test --verbose
